repos:
  # Hook for running black for code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the main branch for the latest version of black
    hooks:
      - id: black
        name: Run Black for code formatting
        language_version: python3  # Use Python 3 interpreter
        stages: [pre-commit]  # Run during pre-commit

  # Hook for running isort for import sorting
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the master branch for the latest version of isort
    hooks:
      - id: isort
        name: Run isort for import sorting
        language_version: python3  # Use Python 3 interpreter
        stages: [pre-commit]  # Run during pre-commit
