repos:
  # Hook for running tox -e format for code formatting (black and isort)
  - repo: local
    hooks:
      - id: tox-format
        name: Run tox -e format for code formatting (black and isort)
        entry: tox -e format
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false  # Ensures tox runs on the entire codebase
        always_run: true       # Runs this hook always, regardless of what files changed

      # Automatically re-stage any files modified by tox -e format
      - id: reformat-staged
        name: Re-stage files after formatting
        entry: git add .
        language: system
        stages: [commit]
        always_run: true

  # Hook for running the standard tox tests
  - repo: local
    hooks:
      - id: run-tox
        name: Run tox tests
        entry: tox
        language: system
        types: [python]
        stages: [commit]
